services:
  symfony_app:
    build: .
    container_name: 1ventaire_app
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:8.0.32
    container_name: 1ventaire_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1ventaire_root_password
      MYSQL_DATABASE: 1ventaire_db
      MYSQL_USER: 1ventaire_user
      MYSQL_PASSWORD: 1ventaire_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: 1ventaire_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - symfony_app

volumes:
  db_data:
